version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  features:
    build:
      context: ./features
    restart: always
    links: 
      - rabbitmq
    depends_on:
      - rabbitmq

  model:
    build:
      context: ./model
    restart: always
    links: 
      - rabbitmq
    depends_on:
      - rabbitmq

  metrics:
    build:
      context: ./metrics
    restart: always
    links: 
      - rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - ./logs:/logs